---
- name: Configure EC2 Instances
  hosts: ec2_instances
  become: yes
  tasks:
  - name: Update package cache and upgrade
    apt:
      update_cache: yes
      upgrade: yes
  - name: Install Nginx
    apt:
      name: nginx
      state: present
  - name: Start Nginx
    service:
      name: nginx
      state: started
      enabled: yes
