---
# tasks file for ec2
- name: start an instance with a public IP address
  vars:
    type: t2.nano
  amazon.aws.ec2_instance:
    name: "ansible-instance"
    # key_name: "prod-ssh-key"
    # vpc_subnet_id: subnet-013744e41e8088axx
    instance_type: "{{type}}"
    security_group: default
    region: ap-south-1
    aws_access_key: "{{ec2_access_key}}" # From vault as defined
    aws_secret_key: "{{ec2_secret_key}}" # From vault as defined
    network:
      assign_public_ip: true
    image_id: ami-0ddfba243cbee3768
    tags:
      Environment: Testing
